model_version: "1.5"
prompt: "Anime drawing of a girl in stylish haute couture outfit in the style of 90's vintage anime, surrealism, masterpiece, best quality, detailed line art, fine details"
unet_max_chunk_size: 4
n_images: 1
denoising_steps: 20
seed: 4259
liked_images: 
    - static/textual_inversion/example_01.png
disliked_images: 
    - static/textual_inversion/image_107_0.png
binary_feedback_type: image_direct

field:
    field_type: kernel  # or "constant_direction"
    guidance_scale: 7
    walk_distance: 1.0
    walk_steps: 100
    flatten_channels: false
additional_args:  # additional parameters specifically for the field and space
    clip_preference_vec: false
    preference_portion: 1.0
    kernel_function: inv_square
