model_id: "stabilityai/stable-diffusion-2-1-base"
prompt: "a beautiful sunset"
neg_prompt: ""
liked_prompts: ["a colorful, green rain forest", "a beautiful lion looking into the camera, high detail", "wild forest"]
disliked_prompts: ["a painting", "orange"]
cfg_scale: 8
steps: 20
seed: 42
device: "auto"