model_id: "stabilityai/stable-diffusion-2-1-base"
prompt: "a beautiful sunset"
neg_prompt: ""
liked_images:
  - static/textual_inversion/example_01.png
disliked_images: []
cfg_scale: 5
steps: 20
seed: 42
device: "auto"
save: all