model_version: "1.5"
# model_ckpt: https://huggingface.co/runwayml/stable-diffusion-v1-5/blob/main/v1-5-pruned-emaonly.ckpt
# model_name: prompthero/openjourney
model_name: dreamlike-art/dreamlike-photoreal-2.0
negative_prompt: lowres, bad anatomy, bad hands, cropped, worst quality
unet_max_chunk_size: 4
n_images: 4
n_rounds: 3
num_prompts: 1000
denoising_steps: 20
seed: null
liked_images:
    # - static/textual_inversion/example_01.png
    # - static/textual_inversion/pink_lights/333573395_746205383847858_1035458537927676333_n.jpg
    # - static/textual_inversion/example_03.png
    # - static/textual_inversion/187265575_screenshot_of_howl_s_moving_castle_by_hayao_miyazaki__studio_ghibli__drawing_of_a_castle_in_the_moun.png
disliked_images:
    # - static/textual_inversion/example_01.png
    # - static/textual_inversion/image_107_0.png
    # - static/generated/example_02.png
    # - static/generated/example_03.png
    # - static/textual_inversion/example_03.png
images_prompts_dir: /data/efedele/stable-preferences/images_prompts
output_path: /data/efedele/stable-preferences